// Это код из методички.
// Здесь паника перехватывается в основной горутине, а вызывается в дополнительно.
// Данная программа завершается аварийно, следовательно перехват не срабатывает.

package main

import (
	"fmt"
	"time"
)

func main() {
	defer func() {
		if v := recover(); v != nil {
			fmt.Println("recovered", v)
		}
	}()

	go func() {
		panic("A-A-A!!!")
	}()

	time.Sleep(time.Second)
	fmt.Println("execution completed")
}
